# Generated by Django 3.2.23 on 2024-06-28 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20240605_0605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramprofile',
            options={'verbose_name': 'telegram профиль', 'verbose_name_plural': 'telegram профили'},
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='био'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='image',
            field=models.ImageField(default='telegram_profiles/default.png', upload_to='telegram_profiles', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
