# Generated by Django 3.2.23 on 2024-06-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240628_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
