# Generated by Django 3.2.23 on 2024-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_telegramprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='токен')),
                ('bot_name', models.CharField(max_length=255, unique=True, verbose_name='Имя телеграм бота')),
            ],
            options={
                'verbose_name': 'Токен доступа телеграм бота',
                'verbose_name_plural': 'Токены доступа телеграм бота',
            },
        ),
    ]
