"""Константы приложения posts."""


DEFAULT_CARD_IMAGE_PATH = 'cards/default/card-logo.png'

DEFAULT_POST_IMAGE = '🐤'

MIN_POST_PRICE = 50

MAX_POST_PRICE = 100_000

MIN_LENGTH_CARD_TITLE = 5

MAX_LENGTH_CARD_TITLE = 48

MAX_LENGTH_CARD_DESCRIPTION = 255

MIN_LENGTH_POST_TITLE = 5

MAX_LENGTH_POST_TITLE = 48

MAX_LENGTH_POST_DESCRIPTION = 600
