# Generated by Django 3.2.23 on 2024-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240617_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.IntegerField(default=0, verbose_name='id телеграм сообщения'),
            preserve_default=False,
        ),
    ]
