# Generated by Django 3.2.23 on 2024-06-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20240628_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='media/cards/default/card-logo.svg', upload_to='cards', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
