# Generated by Django 3.2.23 on 2024-06-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20240628_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/default/card-logo.svg', upload_to='cards', verbose_name='изображение'),
        ),
    ]
