# Generated by Django 3.2.23 on 2024-06-29 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/default/card-logo.png', upload_to='cards', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default='🐤', max_length=1, verbose_name='эмодзи поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='цена'),
        ),
    ]
