# Generated by Django 3.2.23 on 2024-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20240629_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.CharField(max_length=255, verbose_name='id телеграм сообщения в MongoDB'),
        ),
    ]
