# Generated by Django 4.2 on 2024-07-17 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_postpurchase_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardpost',
            options={'ordering': ['created_at'], 'verbose_name': 'карточка-пост', 'verbose_name_plural': 'карточки-посты'},
        ),
        migrations.AddField(
            model_name='cardpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2024-07-17T12:34:56.789123Z', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/default/card-logo.png', upload_to='cards/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='цена'),
        ),
    ]
