# Generated by Django 4.2 on 2024-07-21 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_alter_cardpost_options_cardpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/default/card-logo.png', upload_to='cards', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id телеграм сообщения в MongoDB'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)], verbose_name='цена'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('subscriber_username', models.CharField(max_length=32, unique=True, verbose_name='ник в Telegram')),
                ('subscriber_telegram_id', models.CharField(max_length=32, unique=True, verbose_name='ник в Telegram')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='posts.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'лид',
                'verbose_name_plural': 'лиды',
            },
        ),
    ]
