# Generated by Django 4.2 on 2024-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_card_image_alter_post_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='subscriber_telegram_id',
            field=models.CharField(max_length=32, verbose_name='ник в Telegram'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='subscriber_username',
            field=models.CharField(max_length=32, verbose_name='ник в Telegram'),
        ),
    ]
