# Generated by Django 4.2 on 2024-07-23 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_lead_subscriber_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100000)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='название', max_length=48, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='название'),
        ),
    ]
