# Generated by Django 4.2 on 2024-07-27 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_price_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='название', max_length=48, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='описание', max_length=600, null=True, verbose_name='описание'),
        ),
    ]
